routes/web.php
<?php

use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\GetLocalController;
use App\Http\Controllers\SubscriberController;
use App\Http\Controllers\User\HomepageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\OrderController as UserOrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::controller(HomepageController::class)->group(function () {

    Route::get('/', 'index')->name('homepage');
    Route::get('/about', 'about')->name('about');
    Route::get('/contact', 'contact')->name('contact');
    // Route::get('/blog', 'blog')->name('blog');
    Route::get('/chi-tiet-san-pham/{id}', 'showProduct')->name('home.showproduct');
});

Route::middleware(['auth'])->group(function () {

    Route::controller(HomepageController::class)->group(function () {
        Route::post('/binh-luan/{id}', 'storeComment')->name('home.storecomment');
        Route::get('/danh-sach-yeu-thich', 'showWishlist')->name('home.showwishlist');
        Route::post('/danh-sach-yeu-thich', 'addToWishlist')->name('wishlist.addproduct');
        Route::delete('/danh-sach-yeu-thich/{id}', 'deleteProduct')->name('wishlist.delete');
    });

    Route::controller(CartController::class)->group(function () {
        Route::post('/gio-hang', 'addToCart')->name('cart.addproduct');
        Route::get('/gio-hang', 'show')->name('cart.show');
        Route::put('/gio-hang/cap-nhat', 'update')->name('cart.update');
        Route::delete('/gio-hang/{id}', 'deleteProduct')->name('cart.delete');
        Route::get('/gio-hang/check-coupon', 'checkCoupon')->name('cart.check-coupon');
    });

    Route::controller(CheckoutController::class)->group(function () {
        Route::post('/chi-tiet-don-hang', 'order')->name('checkout.order');
        Route::get('feeship', 'feeShip')->name('feeship');
        Route::get('/thanh-toan', 'index')->name('checkout.index');
    });

    Route::controller(UserOrderController::class)->group(function () {
        Route::get('/quan-ly-don-hang', 'index')->name('home.order');
        Route::get('/chi-tiet-don-hang/{id}', 'show')->name('home.order.show');
    });


    Route::get('/guest/{id}/profile',[HomepageController::class,'showProfile'])->name('showProfile');

    // Admin

    Route::middleware('checklogin')->group(function () {
        Route::get('/home-admin', [HomeController::class, 'index'])->name('home.admin');
        Route::get('/notification', [HomeController::class, 'notification']);
        Route::resource('/category', AdminCategoryController::class)->except('create', 'show');
        Route::resource('/tag', TagController::class)->except('create', 'show');
        Route::resource('/product', AdminProductController::class)->except('create', 'show');
        Route::resource('/coupon', AdminCouponController::class)->except('create', 'show');
        Route::resource('/order', AdminOrderController::class);

        Route::resource('/role', RoleController::class)->except(['show']);
        Route::resource('/dashboard', AdminDashboardController::class);
        Route::get('/manage-user', [UserController::class, 'index'])->name('user.index');
        Route::put('/manage-user/{id}', [UserController::class, 'update'])->name('user.update');
        Route::get('/profile', [AdminProfileController::class, 'index'])->name('admin.profile');
        Route::put('/profile/{id}/update', [AdminProfileController::class, 'update'])->name('admin.updateProfile');

        Route::controller(AdminOrderController::class)->group(function () {
            Route::get('/order', 'index')->name('order.index');
            Route::post('/order/{id}', 'update')->name('order.update');
            Route::get('/order-export', 'orderExport')->name('order.export');
        });

        Route::controller(AdminDashboardController::class)->group(function () {
            Route::post('/filter-by-date', [AdminDashboardController::class, 'filterByDate'])->name('dashboard.filterByDate');
            Route::post('/dashboard-filter', [AdminDashboardController::class, 'dashboardFilter'])->name('dashboard.filter');
            Route::post('/day-order', [AdminDashboardController::class, 'dayOrder'])->name('dashboard.dayOrder');
        });

        Route::controller(PermissionController::class)->group(function () {
            Route::get('/permission/create', 'create')->name('permission.create');
            Route::post('/permission/store', 'store')->name('permission.store');
            Route::get('/get-childrenpermission', 'getChildrenPermission')->name('permission.getChildren');
        });
    });
});


Route::get('subscribe', [SubscriberController::class, 'sendMail'])->name('subscribe');

Route::get('district', [GetLocalController::class, 'district'])->name('district');
Route::get('village', [GetLocalController::class, 'village'])->name('village');

Route::controller(SocialController::class)->group(function () {

    Route::get('auth/google', 'redirectToGoogle')->name('loginGG');
    Route::get('auth/google/callback',  'handleGoogleCallback');


    Route::get('auth/facebook', 'redirectToFacebook')->name('loginFB');
    Route::get('auth/facebook/callback', 'handleFacebookCallback');
});

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->name('forgotPassword');


Route::get('get-password/{id}/{token}',[ForgotPasswordController::class, 'getPassword'])->name('forgotPassword.getPassword');
Route::post('set-password',[ForgotPasswordController::class, 'setPassword'])->name('forgotPassword.setPassword');

resources/views/layouts/admins/footer.blade.php
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        {{-- <span>Copyright &copy; Your Website 2021</span> --}}
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

resources/views/layouts/admins/header.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    {{-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> --}}

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                {{-- <span class="badge badge-danger badge-counter count-notification">{{ countNotifications() }}</span> --}}
            </a>
            <!-- Dropdown - Alerts -->
            <?php
            // $notifies = getNotifications();
            ?>
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in dropdown-notification"
                aria-labelledby="alertsDropdown">
                <div class="childrent1">
                    <h6 class="dropdown-header">
                        {{ __('Alerts Center') }}
                    </h6>
                </div>
                <span class='xx'>
                    <div class="childrent2" style="overflow-y: scroll; width:100%; height:300px;">
                        {{-- @foreach ($notifies as $notify)
                            <a class="dropdown-item d-flex align-items-center notifies" href="{{route('order.index',['order_id'=>$notify->order_id] )}}">
                                <input type="hidden" value="{{$notify->order_id}}" class="order_id">
                                <div class="mr-3">
                                    <div class="icon-circle bg-primary">
                                        <i class="fas fa-file-alt text-white"></i>
                                    </div>
                                </div>
                                <div>
                                    <div class="small text-gray-500">{{ $notify->created_at->diffForHumans(now()) }}
                                    </div>
                                    <span class="font-weight-bold">{{ $notify->content }}</span>
                                </div>
                            </a>
                        @endforeach --}}

                        <a class="dropdown-item text-center small text-gray-500"
                            href="#">{{ __('Show All Alerts') }}</a>
                    </div>
                </span>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                <img class="img-profile rounded-circle" src="{{ Auth::user()->image }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{route('admin.profile')}}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                    @csrf
                </form>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/layouts/admins/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Vegefoods</title>

    <!-- Custom fonts for this template-->
    <link href=" {{ asset('admin/vendor/fontawesome-free/css/all.min.css') }} " rel="stylesheet" type="text/css">
    {{-- <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" /> --}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href=" {{ asset('admin/css/sb-admin-2.min.css') }} " rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('css/toastr.min.css') }}">

    <link href=" {{ asset('admin/css/profile.css') }} " rel="stylesheet">
    <!-- Moriss chart-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        @include('layouts.admins.sidebar')

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                @include('layouts.admins.header')

                @yield('content')
            </div>
            <!-- End of Main Content -->

            @include('layouts.admins.footer')

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Bootstrap core JavaScript-->
    <script src=" {{ asset('admin/vendor/jquery/jquery.min.js') }} "></script>
    <script src=" {{ asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js') }} "></script>

    <!-- Core plugin JavaScript-->
    <script src=" {{ asset('admin/vendor/jquery-easing/jquery.easing.min.js') }} "></script>

    <!-- Custom scripts for all pages-->
    <script src=" {{ asset('admin/js/sb-admin-2.min.js') }} "></script>

    <!-- Page level plugins -->
    <script src=" {{ asset('admin/vendor/chart.js/Chart.min.js') }} "></script>
    <script src=" {{ asset('admin/js/demo/chart-area-demo.js') }} "></script>
    <script src=" {{ asset('admin/js/demo/chart-pie-demo.js') }} "></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{{ asset('js/toastr.min.js') }}"></script>

    {{-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> --}}
    {{-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> --}}

    {{-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> --}}

    {{-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script> --}}

    @yield('script')

    <script type="text/javascript">
        var notificationsWrapper = $('.nav-item dropdown no-arrow mx-1');
        var notificationsToggle = notificationsWrapper.find('a[data-toggle]');
        var notificationsCountElem = $('.count-notification');
        var notificationsCount = parseFloat(notificationsCountElem.text());
        var notifications = $('.dropdown-notification');

        var pusher = new Pusher('5b2b9c3cd9245e856ddb', {
            cluster: "ap1"
        });

        // Subscribe to the channel we specified in our Laravel Event
        var channel = pusher.subscribe('development');

        // Bind a function to a Event (the full Laravel class)
        channel.bind('server.created', function(data) {
            var headerNotifications = $('.childrent1').html();

            var existingNotifications = $('.childrent2');

            // var avatar = Math.floor(Math.random() * (71 - 20 + 1)) + 20;
            var newNotificationHtml = ` 
            <a class="dropdown-item d-flex align-items-center" href="">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">` + data.created_at + `</div>
                        <span class="font-weight-bold">` + data.message + `</span>
                    </div>
                </a>
        `;

            existingNotifications.prepend(newNotificationHtml);
            notificationsCount += 1;
            notificationsCountElem.text(notificationsCount);

        });

        $(document).ready(function() {

            if ('{{ Session::has('success') }}' == 1) {
                showMessage('success', '{{ Session::get('success') }}');

            }

            function showMessage(type, message) {
                setTimeout(function() {
                    toastr.options = {
                        closeButton: true,
                        progressBar: true,
                        showMethod: 'slideDown',
                        timeOut: 4000
                    };
                    if (type == 'success') {
                        toastr.success(message);
                    } else {
                        toastr.error(message);
                    }
                }, 1300);
            }



        })


        function ChangeToSlug(name) {
            var slug;

            slug = $(name).val();

            slug = slug.toLowerCase();
            //Đổi ký tự có dấu thành không dấu
            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
            slug = slug.replace(/đ/gi, 'd');
            //Xóa các ký tự đặt biệt
            slug = slug.replace(
                /\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
            //Đổi khoảng trắng thành ký tự gạch ngang
            slug = slug.replace(/ /gi, "-");
            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
            slug = slug.replace(/\-\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-/gi, '-');
            slug = slug.replace(/\-\-/gi, '-');
            //Xóa các ký tự gạch ngang ở đầu và cuối
            slug = '@' + slug + '@';
            slug = slug.replace(/\@\-|\-\@|\@/gi, '');
            //In slug ra textbox có id “slug”
            $('.convert_slug').val(slug);
        }


        @if (count($errors) > 0)
            $('.bd-example-modal-lg').modal('show');
        @endif
    </script>

</body>

</html>

resources/views/layouts/admins/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home.admin') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="far fa-lemon"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Vegefoods <sup>r</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{request()->segment(1) == 'dashboard' ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('dashboard.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->

    <!-- Nav Item - Pages Collapse Menu -->
    @can('category-list')
    <li class="nav-item {{request()->segment(1) == 'category' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('category.index') }}">
            <i class="fas fa-cubes"></i>
            <span>Categories</span>
        </a>
    </li>
    @endcan
    @can('tag-list')

    <li class="nav-item {{request()->segment(1) == 'tag' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('tag.index') }}">
            <i class="fas fa-tag"></i>
            <span>Tags</span>
        </a>
    </li>
    @endcan
    @can('product-list')

    <li class="nav-item {{request()->segment(1) == 'product' ? 'active' : ''}} ">
        <a class="nav-link collapsed" href="{{ route('product.index') }}">
            <i class="fas fa-cube"></i>
            <span>Products</span>
        </a>
    </li>
    @endcan
    @can('coupon-list')
    <li class="nav-item {{request()->segment(1) == 'coupon' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('coupon.index') }}">
            <i class="fas fa-ticket-alt"></i>
            <span>Coupons</span>
        </a>
    </li>
    @endcan
    @can('order-list')

    <li class="nav-item {{request()->segment(1) == 'order' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('order.index') }}">
            <i class="fas fa-shopping-cart"></i>
            <span>Orders</span>
        </a>
    </li>

    @endcan

    @can('permission-add')

    <li class="nav-item {{request()->segment(1) == 'permission' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('permission.create') }}">
            <i class="fas fa-user-lock"></i>
            <span>{{ __('Permissions')}}</span>
        </a>
    </li>

    @endcan

    @can('role-list')

    <li class="nav-item {{request()->segment(1) == 'role' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('role.index') }}">
            <i class="fas fa-user-shield"></i>
            <span>{{ __('Roles')}}</span>
        </a>
    </li>
    @endcan

    @can('user-list')

    <li class="nav-item {{request()->segment(1) == 'manage-user' ? 'active' : ''}}">
        <a class="nav-link collapsed" href="{{ route('user.index') }}">
            <i class="fas fa-user"></i>
            <span>Users</span>
        </a>
    </li>

    @endcan

    <!-- Nav Item - Utilities Collapse Menu -->
    {{-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-cube"></i>
            <span>Products</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Products:</h6>
                <a class="collapse-item" href="{{ route('product.index') }}">Products List</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#coupons" aria-expanded="true"
            aria-controls="coupons">
            <i class="fas fa-ticket-alt"></i>
            <span>Coupons</span>
        </a>
        <div id="coupons" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Coupons:</h6>
                <a class="collapse-item" href="{{ route('coupon.index') }}">Coupons List</a>
            </div>
        </div>
    </li> --}}
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->