routes/web.php
<?php

use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\GetLocalController;
use App\Http\Controllers\SubscriberController;
use App\Http\Controllers\User\HomepageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\OrderController as UserOrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::controller(HomepageController::class)->group(function () {

    Route::get('/', 'index')->name('homepage');
    Route::get('/about', 'about')->name('about');
    Route::get('/contact', 'contact')->name('contact');
    // Route::get('/blog', 'blog')->name('blog');
    Route::get('/chi-tiet-san-pham/{id}', 'showProduct')->name('home.showproduct');
});

Route::middleware(['auth'])->group(function () {

    Route::controller(HomepageController::class)->group(function () {
        Route::post('/binh-luan/{id}', 'storeComment')->name('home.storecomment');
        Route::get('/danh-sach-yeu-thich', 'showWishlist')->name('home.showwishlist');
        Route::post('/danh-sach-yeu-thich', 'addToWishlist')->name('wishlist.addproduct');
        Route::delete('/danh-sach-yeu-thich/{id}', 'deleteProduct')->name('wishlist.delete');
    });

    Route::controller(CartController::class)->group(function () {
        Route::post('/gio-hang', 'addToCart')->name('cart.addproduct');
        Route::get('/gio-hang', 'show')->name('cart.show');
        Route::put('/gio-hang/cap-nhat', 'update')->name('cart.update');
        Route::delete('/gio-hang/{id}', 'deleteProduct')->name('cart.delete');
        Route::get('/gio-hang/check-coupon', 'checkCoupon')->name('cart.check-coupon');
    });

    Route::controller(CheckoutController::class)->group(function () {
        Route::post('/chi-tiet-don-hang', 'order')->name('checkout.order');
        Route::get('feeship', 'feeShip')->name('feeship');
        Route::get('/thanh-toan', 'index')->name('checkout.index');
    });

    Route::controller(UserOrderController::class)->group(function () {
        Route::get('/quan-ly-don-hang', 'index')->name('home.order');
        Route::get('/chi-tiet-don-hang/{id}', 'show')->name('home.order.show');
    });


    Route::get('/guest/{id}/profile',[HomepageController::class,'showProfile'])->name('showProfile');

    // Admin

    Route::middleware('checklogin')->group(function () {
        Route::get('/home-admin', [HomeController::class, 'index'])->name('home.admin');
        Route::get('/notification', [HomeController::class, 'notification']);
        Route::resource('/category', AdminCategoryController::class)->except('create', 'show');
        Route::resource('/tag', TagController::class)->except('create', 'show');
        Route::resource('/product', AdminProductController::class)->except('create', 'show');
        Route::resource('/coupon', AdminCouponController::class)->except('create', 'show');
        Route::resource('/order', AdminOrderController::class);

        Route::resource('/role', RoleController::class)->except(['show']);
        Route::resource('/dashboard', AdminDashboardController::class);
        Route::get('/manage-user', [UserController::class, 'index'])->name('user.index');
        Route::put('/manage-user/{id}', [UserController::class, 'update'])->name('user.update');
        Route::get('/profile', [AdminProfileController::class, 'index'])->name('admin.profile');
        Route::put('/profile/{id}/update', [AdminProfileController::class, 'update'])->name('admin.updateProfile');

        Route::controller(AdminOrderController::class)->group(function () {
            Route::get('/order', 'index')->name('order.index');
            Route::post('/order/{id}', 'update')->name('order.update');
            Route::get('/order-export', 'orderExport')->name('order.export');
        });

        Route::controller(AdminDashboardController::class)->group(function () {
            Route::post('/filter-by-date', [AdminDashboardController::class, 'filterByDate'])->name('dashboard.filterByDate');
            Route::post('/dashboard-filter', [AdminDashboardController::class, 'dashboardFilter'])->name('dashboard.filter');
            Route::post('/day-order', [AdminDashboardController::class, 'dayOrder'])->name('dashboard.dayOrder');
        });

        Route::controller(PermissionController::class)->group(function () {
            Route::get('/permission/create', 'create')->name('permission.create');
            Route::post('/permission/store', 'store')->name('permission.store');
            Route::get('/get-childrenpermission', 'getChildrenPermission')->name('permission.getChildren');
        });
    });
});


Route::get('subscribe', [SubscriberController::class, 'sendMail'])->name('subscribe');

Route::get('district', [GetLocalController::class, 'district'])->name('district');
Route::get('village', [GetLocalController::class, 'village'])->name('village');

Route::controller(SocialController::class)->group(function () {

    Route::get('auth/google', 'redirectToGoogle')->name('loginGG');
    Route::get('auth/google/callback',  'handleGoogleCallback');


    Route::get('auth/facebook', 'redirectToFacebook')->name('loginFB');
    Route::get('auth/facebook/callback', 'handleFacebookCallback');
});

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->name('forgotPassword');


Route::get('get-password/{id}/{token}',[ForgotPasswordController::class, 'getPassword'])->name('forgotPassword.getPassword');
Route::post('set-password',[ForgotPasswordController::class, 'setPassword'])->name('forgotPassword.setPassword');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'display_name'];

    public function users() 
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions() 
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Services\RoleService;
use App\Services\PermissionService;
use Exception;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $roleService;
    protected $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
        $this->middleware('can:role-list')->only('index');
        $this->middleware('can:role-edit')->only('edit','update');
        $this->middleware('can:role-delete')->only('destroy');
        $this->middleware('can:role-add')->only('store', 'create');
    }

    public function index(Request $request)
    {
        $data = $request->all();
        
        $roles = $this->roleService->getRoles($data);

        return view('admins.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parentPermissions = $this->permissionService->getParentPermissions();

        return view('admins.roles.create', compact('parentPermissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $data = $request->all();
            DB::beginTransaction();

            $this->roleService->saveRole($data);

            DB::commit();

            return redirect()->route('role.index')->with('success', 'Create role successfuly');
        } catch (Exception $e) {
            DB::rollBack();
            
            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = $this->roleService->getRoleById($id);
        $parentPermissions = $this->permissionService->getParentPermissions();

        return view('admins.roles.edit', compact('role', 'parentPermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $data = $request->all();
            DB::beginTransaction();

            $this->roleService->updateRole($data, $id);

            DB::commit();

            return redirect()->route('role.index')->with('success', 'Update role successfuly');
        } catch (Exception $e) {
            DB::rollBack();
            
            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $this->roleService->deleteRoleById($id);
            DB::commit();

            return redirect()->route('role.index')->with('success', 'Delete role successfully');
        } catch (Exception $e) {
            DB::rollBack();
            
            return redirect()->route('role.index')->with('error', $e->getMessage());
        }
    }
}

resources/views/admins/roles/create.blade.php
@extends('layouts.admins.main')
@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home.admin') }}">{{ __('Home') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('role.index') }}">{{ __('List Roles') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ __('Create Role') }}</li>
            </ol>
        </nav>
        <div class="card shadow mb-4">


            <div class="card-body">

                <div id="content">
                    <form method="post" class="form-horizontal" id="form" action="{{ route('role.store') }}"
                        enctype="multipart/form-data">
                        @csrf
                        <div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-12 control-label">{{ __('Name') }} <i
                                        class="note"><span class="text-danger">*</span></i></label>
                                <div class="col-sm-12"><input type="text" class="form-control" id="name" name="name"
                                        value="{{ old('name') }}"> <span class="help-block m-b-none"></span>
                                </div>
                            </div>
                            @error('name')
                                <span class="errors text-danger">{{ $message }}</span>
                            @enderror
                            <div class="hr-line-dashed"></div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-12 control-label">{{ __('Display_name') }} <i
                                        class="note"><span class="text-danger">*</span></i></label>
                                <div class="col-sm-12">
                                    <textarea type="text" class="form-control" name="display_name" value="{{ old('display_name') }}"> </textarea> <span class="help-block m-b-none"></span>
                                </div>
                            </div>
                            @error('display_name')
                                <span class="errors text-danger">{{ $message }}</span>
                            @enderror

                            <div class="form-group">
                                <h5 class="card-title col-md-3">
                                    <label>

                                        <input type="checkbox" class="form-group checkall" value="">
                                    </label>
                                    {{ __('Check all') }}
                                </h5>
                            </div>


                            <div class="form-group">
                                <h5 class="card-title col-md-3">
                                    <label>

                                        <input type="checkbox" class="form-group" name="permission_id[]" value="1"
                                            checked>
                                    </label>
                                    {{ __('Login Admin') }}
                                </h5>
                            </div>
                            @foreach ($parentPermissions as $parentPermission)
                                <div class="hr-line-dashed"></div>

                                <div class="col-md-12 form-group">

                                    <div class="card">
                                        <div class="card-header">
                                            <label>
                                                <input type="checkbox" class="parentPermission form-group" value="">
                                            </label>
                                            {{ $parentPermission->name }}
                                        </div>

                                        <div class="card-body">
                                            <div class="row">

                                                @foreach ($parentPermission->childrentPermissions as $childrentPermission)
                                                    <h5 class="card-title col-md-3">
                                                        <label>
                                                            <input type="checkbox" name="permission_id[]"
                                                                class="form-group childrentPermission "
                                                                value="{{ $childrentPermission->id }}">
                                                        </label>
                                                        {{ $childrentPermission->name }}
                                                    </h5>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                {{-- <br> --}}
                            @endforeach
                            <div class="col-md-12 form-group">
                                <a href="{{ route('role.index') }}" class="btn btn-primary">{{ __('Back') }}</a>
                                <button class="btn btn-primary" type="submit">{{ __('Create') }}</button>


                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {


            $('.parentPermission').change(function() {
                if ($(this).is(':checked')) {
                    $(this).closest('.card').find('.childrentPermission').prop('checked', true);
                } else {

                    $(this).closest('.card').find('.childrentPermission').prop('checked', false);
                }
            })

            $('.childrentPermission').change(function() {
                if ($(this).closest('.row').find('.childrentPermission:checked').length == $(this).closest(
                        '.row').find(
                        '.childrentPermission').length) {
                    $(this).closest('.card').find('.parentPermission').prop('checked', true);
                } else {
                    $(this).closest('.card').find('.parentPermission').prop('checked', false);
                }
            })

            $('.checkall').change(function() {
                if ($(this).is(':checked')) {

                    $('.childrentPermission').prop('checked', true);
                    $('.parentPermission').prop('checked', true);
                } else {
                    $('.childrentPermission').prop('checked', false);
                    $('.parentPermission').prop('checked', false);
                }
            })

        })
    </script>
@endsection

resources/views/admins/roles/index.blade.php
@extends('layouts.admins.main')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="card shadow mb-4">
            <div style="display: flex" class="card-header py-3">
                <a style="text-decoration: none" href="{{ route('home.admin') }}" class="">Home /</a>
                <a href="{{ route('role.index') }}" style="margin-left:5px; text-decoration: none"
                    class="font-weight-bold text-primary">Roles List</a>

            </div>

            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                    action="{{ route('role.index') }}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" id="search" name="search" value="{{ Request::get('search') }}"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                   
                    <div style="margin: 14px 0px 0px 0px" class="col-sm-2">
                        <div class="form-group">
                            <div style="display: flex;" class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-primary" href="{{ route('role.create') }}"><i
                                        class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </ul>
            </nav>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>{{ __('ID') }}</th>
                                <th>{{ __('Name') }}</th>
                                <th>{{ __('Display_name') }}</th>
                                <th>{{ __('Permission') }}</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($roles)
                                @foreach ($roles as $role)
                                    <tr>
                                        <td>{{ $role->id }}</td>
                                        <td>{{ $role->name }}</td>
                                        <td>{{ $role->display_name }}</td>
                                        <td>
                                            @foreach ($role->permissions as $permission)
                                            <span class="badge badge-secondary"> {{ $permission->name }} </span>
                                            @endforeach
                                        </td>
                                        <td>
                                            <div style="display: flex">
                                                <button style=" width: 35px; height: 35px;" type="button"
                                                    class="btn btn-primary btn-sm"><a style="color: white ;"
                                                        href="{{ route('role.edit', [$role->id]) }}"
                                                        class="ac-button">
                                                        <span class="far fa-edit"></span></a></button>

                                                <form action="{{ route('role.destroy', [$role->id]) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button style=" width: 35px; height: 35px; margin-left: 5px"
                                                        type="submit" class="btn btn-danger btn-sm"
                                                        onclick="return confirm('Are you sure you want to delete this role ?')">
                                                        <span class="far fa-trash-alt"></span></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>
            </div>
            @if ($roles)
                {{ $roles->appends(request()->query())->links('vendor.pagination.custom') }}
            @endif
        </div>
    </div>
@endsection