routes/web.php
<?php

use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\GetLocalController;
use App\Http\Controllers\SubscriberController;
use App\Http\Controllers\User\HomepageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\OrderController as UserOrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::controller(HomepageController::class)->group(function () {

    Route::get('/', 'index')->name('homepage');
    Route::get('/about', 'about')->name('about');
    Route::get('/contact', 'contact')->name('contact');
    // Route::get('/blog', 'blog')->name('blog');
    Route::get('/chi-tiet-san-pham/{id}', 'showProduct')->name('home.showproduct');
});

Route::middleware(['auth'])->group(function () {

    Route::controller(HomepageController::class)->group(function () {
        Route::post('/binh-luan/{id}', 'storeComment')->name('home.storecomment');
        Route::get('/danh-sach-yeu-thich', 'showWishlist')->name('home.showwishlist');
        Route::post('/danh-sach-yeu-thich', 'addToWishlist')->name('wishlist.addproduct');
        Route::delete('/danh-sach-yeu-thich/{id}', 'deleteProduct')->name('wishlist.delete');
    });

    Route::controller(CartController::class)->group(function () {
        Route::post('/gio-hang', 'addToCart')->name('cart.addproduct');
        Route::get('/gio-hang', 'show')->name('cart.show');
        Route::put('/gio-hang/cap-nhat', 'update')->name('cart.update');
        Route::delete('/gio-hang/{id}', 'deleteProduct')->name('cart.delete');
        Route::get('/gio-hang/check-coupon', 'checkCoupon')->name('cart.check-coupon');
    });

    Route::controller(CheckoutController::class)->group(function () {
        Route::post('/chi-tiet-don-hang', 'order')->name('checkout.order');
        Route::get('feeship', 'feeShip')->name('feeship');
        Route::get('/thanh-toan', 'index')->name('checkout.index');
    });

    Route::controller(UserOrderController::class)->group(function () {
        Route::get('/quan-ly-don-hang', 'index')->name('home.order');
        Route::get('/chi-tiet-don-hang/{id}', 'show')->name('home.order.show');
    });


    Route::get('/guest/{id}/profile',[HomepageController::class,'showProfile'])->name('showProfile');

    // Admin

    Route::middleware('checklogin')->group(function () {
        Route::get('/home-admin', [HomeController::class, 'index'])->name('home.admin');
        Route::get('/notification', [HomeController::class, 'notification']);
        Route::resource('/category', AdminCategoryController::class)->except('create', 'show');
        Route::resource('/tag', TagController::class)->except('create', 'show');
        Route::resource('/product', AdminProductController::class)->except('create', 'show');
        Route::resource('/coupon', AdminCouponController::class)->except('create', 'show');
        Route::resource('/order', AdminOrderController::class);

        Route::resource('/role', RoleController::class)->except(['show']);
        Route::resource('/dashboard', AdminDashboardController::class);
        Route::get('/manage-user', [UserController::class, 'index'])->name('user.index');
        Route::put('/manage-user/{id}', [UserController::class, 'update'])->name('user.update');
        Route::get('/profile', [AdminProfileController::class, 'index'])->name('admin.profile');
        Route::put('/profile/{id}/update', [AdminProfileController::class, 'update'])->name('admin.updateProfile');

        Route::controller(AdminOrderController::class)->group(function () {
            Route::get('/order', 'index')->name('order.index');
            Route::post('/order/{id}', 'update')->name('order.update');
            Route::get('/order-export', 'orderExport')->name('order.export');
        });

        Route::controller(AdminDashboardController::class)->group(function () {
            Route::post('/filter-by-date', [AdminDashboardController::class, 'filterByDate'])->name('dashboard.filterByDate');
            Route::post('/dashboard-filter', [AdminDashboardController::class, 'dashboardFilter'])->name('dashboard.filter');
            Route::post('/day-order', [AdminDashboardController::class, 'dayOrder'])->name('dashboard.dayOrder');
        });

        Route::controller(PermissionController::class)->group(function () {
            Route::get('/permission/create', 'create')->name('permission.create');
            Route::post('/permission/store', 'store')->name('permission.store');
            Route::get('/get-childrenpermission', 'getChildrenPermission')->name('permission.getChildren');
        });
    });
});


Route::get('subscribe', [SubscriberController::class, 'sendMail'])->name('subscribe');

Route::get('district', [GetLocalController::class, 'district'])->name('district');
Route::get('village', [GetLocalController::class, 'village'])->name('village');

Route::controller(SocialController::class)->group(function () {

    Route::get('auth/google', 'redirectToGoogle')->name('loginGG');
    Route::get('auth/google/callback',  'handleGoogleCallback');


    Route::get('auth/facebook', 'redirectToFacebook')->name('loginFB');
    Route::get('auth/facebook/callback', 'handleFacebookCallback');
});

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->name('forgotPassword');


Route::get('get-password/{id}/{token}',[ForgotPasswordController::class, 'getPassword'])->name('forgotPassword.getPassword');
Route::post('set-password',[ForgotPasswordController::class, 'setPassword'])->name('forgotPassword.setPassword');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug'];

    public function products() {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\TagService;
use App\Http\Requests\TagRequest;
use Exception;
use Illuminate\Support\Facades\DB;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $tagService;

    public function __construct(TagService $tagService)
    {
        $this->tagService = $tagService;
        $this->middleware('can:tag-list')->only('index');
        $this->middleware('can:tag-edit')->only('edit','update');
        $this->middleware('can:tag-delete')->only('destroy');
        $this->middleware('can:tag-add')->only('store');
    }

    public function index(Request $request)
    {
        $data = $request->all();
        $tags = $this->tagService->showTag($data);

        return view('admins.tags.index', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        try {
            $data = $request->all();
            $this->tagService->saveTag($data);

            return redirect()->route('tag.index')->with('success', 'Create tag successfully!');
        } catch (Exception $e) {

            return redirect()->route('tag.index')->with('error', $e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $tag = $this->tagService->findTagBySlug($slug);

        return view('admins.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, $slug)
    {
        try {
            $data = $request->all();

            $this->tagService->updateTag($data, $slug);

            return redirect()->route('tag.index')->with('success', 'Update this tag successfully');
        } catch (Exception $e) {

            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();

            $this->tagService->deleteTagById($id);

            DB::commit();

            return redirect()->back()->with('success', 'Delete tag successfully');
        } catch (Exception $e) {
            DB::rollBack();

            return redirect()->back()->with('error', $e->getMessage());
        };
    }
}

resources/views/admins/tags/edit.blade.php
@extends('layouts.admins.main')
@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <a style="text-decoration: none" href="{{ route('home.admin') }}" class="">Home /</a>
                <a href="{{ route('tag.index') }}" style="margin-left:5px; text-decoration: none"
                    class="font-weight-bold text-primary">Tags List</a>
                <h6 class="m-0 font-weight-bold text-primary">Tag {{ $tag->name }} Edit</h6>
            </div>

            <form method="post" class="form-horizontal" action="{{ route('tag.update', [$tag->slug]) }}"
                enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div style="text-align: center ; margin-top: 30px">
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">Name <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-7"><input type="text"
                                class="form-control name" name="name" onkeyup="ChangeToSlug(this)"
                                value="{{ old('name', $tag->name) }}"> <span class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('name')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">Slug <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-7"><input type="text"
                                class="form-control convert_slug" name="slug" value="{{ old('slug', $tag->slug) }}"> <span
                                class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('slug')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div style="margin-left : 700px" class="col-lg-21">
                            <button class="btn btn-primary" type="submit">Update</button>
                            <a class="btn btn-info " href="{{ route('tag.index') }}">Back</a>
                        </div>
                    </div>
            </form>

        </div>
    </div>
    </div>
@endsection

resources/views/admins/tags/index.blade.php
@extends('layouts.admins.main')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="card shadow mb-4">
            <div style="display: flex" class="card-header py-3">
                {{-- <h6 class="m-0 font-weight-bold text-primary">Home</h6> --}}
                <a style="text-decoration: none" href="{{ route('home.admin') }}" class="">Home /</a>
                <a href="{{ route('tag.index') }}" style="margin-left:5px; text-decoration: none"
                    class="font-weight-bold text-primary">Tags List</a>
                {{-- <h6 style="display: flex" class="m-0 font-weight-bold text-primary">tags List</h6> --}}

            </div>

            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                    action="{{ route('tag.index') }}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" id="search" name="search" value="{{ Request::get('search') }}"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                            aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                        placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>
                    <div style="margin: 14px 0px 0px 0px" class="col-sm-2">
                        <div class="form-group">
                            <div style="display: flex;" class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-primary" href="" data-toggle="modal" data-target=".bd-example-modal-lg"><i
                                        class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </ul>



            </nav>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>{{ __('Slug')}}</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($tags as $tag)
                                <tr>
                                    <td>{{ $tag->id }}</td>
                                    <td>{{ $tag->name }}</td>
                                    <td>{{ $tag->slug }}</td>
                                    <td>
                                        <div style="display: flex">
                                            <button style=" width: 35px; height: 35px;" type="button"
                                                class="btn btn-primary btn-sm"><a style="color: white ;"
                                                    href="{{ route('tag.edit', [$tag->slug]) }}"
                                                    class="ac-button">
                                                    <span class="far fa-edit"></span></a></button>

                                            <form action="{{ route('tag.destroy', [$tag->id]) }}"
                                                method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button style=" width: 35px; height: 35px; margin-left: 5px" type="submit"
                                                    class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Are you sure you want to delete this tag ?')">
                                                    <span class="far fa-trash-alt"></span></button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
            {{ $tags->appends(request()->query())->links('vendor.pagination.custom') }}
        </div>
    </div>


    <!-- Extra large modal -->
    <div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create tags</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">



                    <div class="ibox-content">
                        <form method="post" class="form-horizontal" id="form" action="{{ route('tag.store') }}"
                            enctype="multipart/form-data">
                            @csrf
                            <div style="text-align: center">
                                <div class="hr-line-dashed"></div>
                                <div class="form-group"><label class="col-sm-2 control-label">Name <i
                                            class="note text-danger">*</i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="text"
                                            class="form-control name" id="name" name="name" onkeyup="ChangeToSlug(this)"  value="{{ old('name') }}"> <span
                                            class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('name')
                                    <span  class="errors text-danger">{{ $message }}</span>
                                @enderror
                                <div class="form-group"><label class="col-sm-2 control-label">{{ __('Slug')}} <i
                                            class="note"><span class="text-danger">*</span></i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="text"
                                            class="form-control convert_slug" name="slug" value="{{ old('slug') }}"> <span
                                            class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('slug')
                                    <span class="errors text-danger">{{ $message }}</span>
                                @enderror

                           
                            <div class="hr-line-dashed"></div>
                            <div class="modal-footer">
                                <button class="btn btn-primary" type="submit" id="submit" name="submit">Create</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                            </div>
                        </form>
                        <div id="message"></div>
                    </div>


                </div>
            </div>
        </div>
    </div>
@endsection