routes/web.php
<?php

use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\GetLocalController;
use App\Http\Controllers\SubscriberController;
use App\Http\Controllers\User\HomepageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\OrderController as UserOrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::controller(HomepageController::class)->group(function () {

    Route::get('/', 'index')->name('homepage');
    Route::get('/about', 'about')->name('about');
    Route::get('/contact', 'contact')->name('contact');
    // Route::get('/blog', 'blog')->name('blog');
    Route::get('/chi-tiet-san-pham/{id}', 'showProduct')->name('home.showproduct');
});

Route::middleware(['auth'])->group(function () {

    Route::controller(HomepageController::class)->group(function () {
        Route::post('/binh-luan/{id}', 'storeComment')->name('home.storecomment');
        Route::get('/danh-sach-yeu-thich', 'showWishlist')->name('home.showwishlist');
        Route::post('/danh-sach-yeu-thich', 'addToWishlist')->name('wishlist.addproduct');
        Route::delete('/danh-sach-yeu-thich/{id}', 'deleteProduct')->name('wishlist.delete');
    });

    Route::controller(CartController::class)->group(function () {
        Route::post('/gio-hang', 'addToCart')->name('cart.addproduct');
        Route::get('/gio-hang', 'show')->name('cart.show');
        Route::put('/gio-hang/cap-nhat', 'update')->name('cart.update');
        Route::delete('/gio-hang/{id}', 'deleteProduct')->name('cart.delete');
        Route::get('/gio-hang/check-coupon', 'checkCoupon')->name('cart.check-coupon');
    });

    Route::controller(CheckoutController::class)->group(function () {
        Route::post('/chi-tiet-don-hang', 'order')->name('checkout.order');
        Route::get('feeship', 'feeShip')->name('feeship');
        Route::get('/thanh-toan', 'index')->name('checkout.index');
    });

    Route::controller(UserOrderController::class)->group(function () {
        Route::get('/quan-ly-don-hang', 'index')->name('home.order');
        Route::get('/chi-tiet-don-hang/{id}', 'show')->name('home.order.show');
    });


    Route::get('/guest/{id}/profile',[HomepageController::class,'showProfile'])->name('showProfile');

    // Admin

    Route::middleware('checklogin')->group(function () {
        Route::get('/home-admin', [HomeController::class, 'index'])->name('home.admin');
        Route::get('/notification', [HomeController::class, 'notification']);
        Route::resource('/category', AdminCategoryController::class)->except('create', 'show');
        Route::resource('/tag', TagController::class)->except('create', 'show');
        Route::resource('/product', AdminProductController::class)->except('create', 'show');
        Route::resource('/coupon', AdminCouponController::class)->except('create', 'show');
        Route::resource('/order', AdminOrderController::class);

        Route::resource('/role', RoleController::class)->except(['show']);
        Route::resource('/dashboard', AdminDashboardController::class);
        Route::get('/manage-user', [UserController::class, 'index'])->name('user.index');
        Route::put('/manage-user/{id}', [UserController::class, 'update'])->name('user.update');
        Route::get('/profile', [AdminProfileController::class, 'index'])->name('admin.profile');
        Route::put('/profile/{id}/update', [AdminProfileController::class, 'update'])->name('admin.updateProfile');

        Route::controller(AdminOrderController::class)->group(function () {
            Route::get('/order', 'index')->name('order.index');
            Route::post('/order/{id}', 'update')->name('order.update');
            Route::get('/order-export', 'orderExport')->name('order.export');
        });

        Route::controller(AdminDashboardController::class)->group(function () {
            Route::post('/filter-by-date', [AdminDashboardController::class, 'filterByDate'])->name('dashboard.filterByDate');
            Route::post('/dashboard-filter', [AdminDashboardController::class, 'dashboardFilter'])->name('dashboard.filter');
            Route::post('/day-order', [AdminDashboardController::class, 'dayOrder'])->name('dashboard.dayOrder');
        });

        Route::controller(PermissionController::class)->group(function () {
            Route::get('/permission/create', 'create')->name('permission.create');
            Route::post('/permission/store', 'store')->name('permission.store');
            Route::get('/get-childrenpermission', 'getChildrenPermission')->name('permission.getChildren');
        });
    });
});


Route::get('subscribe', [SubscriberController::class, 'sendMail'])->name('subscribe');

Route::get('district', [GetLocalController::class, 'district'])->name('district');
Route::get('village', [GetLocalController::class, 'village'])->name('village');

Route::controller(SocialController::class)->group(function () {

    Route::get('auth/google', 'redirectToGoogle')->name('loginGG');
    Route::get('auth/google/callback',  'handleGoogleCallback');


    Route::get('auth/facebook', 'redirectToFacebook')->name('loginFB');
    Route::get('auth/facebook/callback', 'handleFacebookCallback');
});

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->name('forgotPassword');


Route::get('get-password/{id}/{token}',[ForgotPasswordController::class, 'getPassword'])->name('forgotPassword.getPassword');
Route::post('set-password',[ForgotPasswordController::class, 'setPassword'])->name('forgotPassword.setPassword');

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Coupon extends Model
{
    use HasFactory;

    protected $primaryKey = 'code';
    public $incrementing = false;
    
    protected $keyType = 'string';

    protected $fillable = [
        'code',
        'value',
        'start_date',
        'end_date'
    ];

    const PAGINATE = '10';

    public function users()
    {
        return $this->belongsToMany(User::class, 'coupon_user', 'user_id', 'coupon_code');
    }
}

app/Http/Controllers/Admin/CouponController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\CouponRequest;
use App\Models\Coupon;
use Carbon\Carbon;
use Exception;

class CouponController extends Controller
{

    public function __construct()
    {
        $this->middleware('can:coupon-list')->only('index');
        $this->middleware('can:coupon-edit')->only('edit','update');
        $this->middleware('can:coupon-delete')->only('destroy');
        $this->middleware('can:coupon-add')->only('store');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = $request->all();
        $coupons = Coupon::orderBy('coupons.code','DESC');
        if ($request->ajax()) {
            $output = '';
            $coupons = $coupons->where(function($query) use($data){
                $query->orWhere('code',''.$data['search']);
            })->get();
        if ($coupons) {
            foreach ($coupons as $key => $coupon) {
                $output .= '<tr>
                <td>'.$coupon->code.'</td>
                <td>'.$coupon->value .'</td>
                <td>'. $coupon->start_date .'</td>
                <td>'.$coupon->end_date .'</td>
                <td>
                    <div style="display: flex">
                        <button style=" width: 35px; height: 35px;" type="button"
                            class="btn btn-primary btn-sm"><a style="color: white ;"
                                href='.route("coupon.edit", [$coupon->code]).'
                                class="ac-button">
                                <span class="far fa-edit"></span></a></button>

                        <form action='.route("coupon.destroy", [$coupon->code]).' method="DELETE">
                            <button style=" width: 35px; height: 35px; margin-left: 5px" type="submit"
                                class="btn btn-danger btn-sm"
                                onclick="return confirm("Are you sure you want to delete this category ?")">
                                <span class="far fa-trash-alt"></span></button>
                        </form>
                    </div>
                </td>
                </tr>';
            }
        }
        return Response($output);
    }
        $coupons = $coupons->paginate(config('paginate.paginate'));
        
        return view('admins.coupons.index',compact('coupons'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CouponRequest $request)
    {
        try{

            $data = $request->all();
            $coupon = new Coupon();
            $coupon = $coupon->fill($data)->save();

            return redirect()->route('coupon.index')->with('success','Create coupon data successfully');
        } catch(Exception $e) {

            return redirect()->route('coupon.index')->with('error', $e->getMessage());
        }

        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($code)
    {
        $coupon = Coupon::find($code);

        return view('admins.coupons.edit',compact('coupon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $code)
    {
        try { 
           
            $data = $request->all();
            $coupon = Coupon::find($code); 
            $coupon->fill($data)->save();
        } catch(Exception $e) {

            return redirect()->route('coupon.index')->with('error','Update coupon data failed !');
        }
        return redirect()->route('coupon.index')->with('success','Update coupon data successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($code)
    {
        $coupon = Coupon::find($code);
        if (!$coupon) {
            
            return redirect()->route('coupon.index')->with('error','Delete coupon data failed !');
        }else{
            $coupon->delete();

            return redirect()->route('coupon.index')->with('success','Delete coupon data successfully');
        }
    }
}

resources/views/admins/coupons/edit.blade.php
@extends('layouts.admins.main')
@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Coupon {{ $coupon->code }} Edit</h6>
            </div>

            <form method="post" class="form-horizontal" action="{{ route('coupon.update', [$coupon->code]) }}"
                enctype="multipart/form-data">
                @csrf
                @method('PUT')
                {{-- <input type="hidden" name="id" value="{{ $student->id }}"> --}}
                <div style="text-align: center ; margin-top: 30px">
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">Code <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-9"><input type="text" class="form-control"
                                id="code" name="code" value="{{ old('code', $coupon->code) }}"> <span
                                class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('code')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">Value <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-9"><input type="text" class="form-control"
                                id="value" name="value" value="{{ old('value', $coupon->value) }}">
                            <span class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('value')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">Start Date <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-9"><input type="date" class="form-control"
                                id="start_date" name="start_date" value="{{ old('start_date', $coupon->start_date) }}">
                            <span class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('start_date')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">End Date <i
                                class="note text-danger">*</i></label>
                        <div style="display: inline-block" class="col-sm-9"><input type="date" class="form-control"
                                id="end_date" name="end_date" value="{{ old('end_date', $coupon->end_date) }}"> <span
                                class="help-block m-b-none"></span>
                        </div>
                    </div>
                    @error('end_date')
                        <span class="errors text-danger">{{ $message }}</span>
                    @enderror
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div style="margin-left : 900px" class="col-lg-21">
                            <button class="btn btn-primary" type="submit" name="update">Update</button>
                            <a class="btn btn-info " href="{{ route('category.index') }}">Back</a>
                        </div>
                    </div>
            </form>

        </div>
    </div>
    </div>
@endsection

resources/views/admins/coupons/index.blade.php
@extends('layouts.admins.main')
@section('content')
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="card shadow mb-4">
            <div style="display: flex" class="card-header py-3">
                {{-- <h6 class="m-0 font-weight-bold text-primary">Home</h6> --}}
                <a style="text-decoration: none" href="{{ route('home.admin') }}" class="">Home /</a>
                <a href="{{ route('coupon.index') }}" style="margin-left:5px; text-decoration: none"
                    class="font-weight-bold text-primary">Coupons List</a>
                {{-- <h6 style="display: flex" class="m-0 font-weight-bold text-primary">Categories List</h6> --}}

            </div>

            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                    action="{{ route('coupon.index') }}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" id="search" name="search" value="{{ Request::get('search') }}"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">\

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <div style="margin: 14px 0px 0px 0px" class="col-sm-2">
                        <div class="form-group">
                            <div style="display: flex;" class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-primary" href="" data-toggle="modal" data-target=".bd-example-modal-lg"><i
                                        class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </ul>



            </nav>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Value</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($coupons != null)
                                @foreach ($coupons as $key => $coupon)
                                    <tr>
                                        <td>{{ $coupon->code }}</td>
                                        <td>{{ $coupon->value }}</td>
                                        <td>{{ $coupon->start_date }}</td>
                                        <td>{{ $coupon->end_date }}</td>
                                        <td>
                                            <div style="display: flex">
                                                <button style=" width: 35px; height: 35px;" type="button"
                                                    class="btn btn-primary btn-sm"><a style="color: white ;"
                                                        href="{{ route('coupon.edit', [$coupon->code]) }}"
                                                        class="ac-button">
                                                        <span class="far fa-edit"></span></a></button>

                                                <form action="{{ route('coupon.destroy', [$coupon->code]) }}"
                                                    method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button style=" width: 35px; height: 35px; margin-left: 5px"
                                                        type="submit" class="btn btn-danger btn-sm"
                                                        onclick="return confirm('Are you sure you want to delete this coupon ?')">
                                                        <span class="far fa-trash-alt"></span></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
            {{ $coupons->appends(request()->query())->links('vendor.pagination.custom') }}
        </div>
    </div>


    <!-- Extra large modal -->
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Categories</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">



                    <div class="ibox-content">
                        <form method="post" class="form-horizontal" id="form" action="{{ route('coupon.store') }}">
                            @csrf
                            <div style="text-align: center">
                                <div class="hr-line-dashed"></div>
                                <div class="form-group"><label class="col-sm-2 control-label">Code <i
                                            class="note text-danger">*</i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="text"
                                            class="form-control" id="code" name="code" value="{{ old('code') }}"> <span
                                            class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('code')
                                    <span class="errors text-danger">{{ $message }}</span>
                                @enderror

                                <div class="hr-line-dashed"></div>
                                <div class="form-group"><label class="col-sm-2 control-label">Value <i
                                            class="note text-danger">*</i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="text"
                                            class="form-control" id="value" name="value" value="{{ old('value') }}">
                                        <span class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('value')
                                    <span class="errors text-danger">{{ $message }}</span>
                                @enderror

                                <div class="hr-line-dashed"></div>
                                <div class="form-group"><label class="col-sm-2 control-label">Start Date <i
                                            class="note text-danger">*</i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="date"
                                            class="form-control" id="start_date" name="start_date"
                                            value="{{ old('start_date') }}"> <span class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('start_date')
                                    <span class="errors text-danger">{{ $message }}</span>
                                @enderror

                                <div class="hr-line-dashed"></div>
                                <div class="form-group"><label class="col-sm-2 control-label">End Date <i
                                            class="note text-danger">*</i></label>
                                    <div style="display: inline-block" class="col-sm-9"><input type="date"
                                            class="form-control" id="end_date" name="end_date"
                                            value="{{ old('end_date') }}"> <span class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                @error('end_date')
                                    <span class="errors text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="modal-footer">
                                <button class="btn btn-primary" type="submit" id="submit" name="submit">Create</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                            </div>
                        </form>
                        <div id="message"></div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <script>
        $('#myModal').on('shown.bs.modal', function() {
            $('#myInput').trigger('focus')
        })
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        $('#search').on('keyup', function() {
            $value = $(this).val();
            $.ajax({
                type: 'get',
                url: '{{ URL::to('coupon') }}',
                data: {
                    'search': $value
                },
                success: function(data) {
                    $('tbody').html(data);
                }
            });
        })
        $.ajaxSetup({
            headers: {
                'csrftoken': '{{ csrf_token() }}'
            }
        });
    </script>
@endsection